name: Setup and Build CDKTF
description: Shared setup steps for deploying or destroying CKDTF resources
inputs:
  aws-access-key-id:
    description: AWS Access Key ID
    required: true
  aws-secret-access-key:
    description: AWS Secret Access Key
    required: true
  aws-region:
    description: AWS Default Region
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 24
        cache: npm
        cache-dependency-path: iac/package-lock.json
    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v3
    - name: Install cdktf cli
      shell: bash
      run: npm install -g cdktf-cli   
    - name: Install CDKTF dependencies
      working-directory: ./iac
      shell: bash
      run: npm install      
    - name: Get providers
      working-directory: ./iac
      shell: bash
      run: npm run get
    - name: Synthesize CDKTF
      working-directory: ./iac
      run: npm run synth
      shell: bash
