services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports: ["3000:3000"]
    command: ["npm", "run", "dev"] # Use the npm dev script for dev work
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    image: app-server
    healthcheck:
      test: ["CMD", "sh", "-c", "wget --spider --no-verbose --server-response http://localhost:3000/health"]
      interval: 30s
      timeout: 30s
      retries: 1
      start_period: 30s
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules 