name: Destroy Infrastructure

on:
  workflow_dispatch:

jobs:
  destroy-infrastructure:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup and Build CDKTF
        uses: ./.github/actions/setup-cdktf
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
      
      - name: Destroy infrastructure
        working-directory: ./iac
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          TERRAFORM_STATE_BUCKET: ${{ vars.TERRAFORM_STATE_BUCKET }}
          ECR_REPOSITORY_NAME: ${{ vars.ECR_REPOSITORY_NAME }}
          ECR_IMAGE_TAG_MUTABILITY: ${{ vars.ECR_IMAGE_TAG_MUTABILITY }}
          ECR_SCAN_ON_PUSH: ${{ vars.ECR_SCAN_ON_PUSH }}
          ECR_IMAGE_TAG: ${{ vars.ECR_IMAGE_TAG }}
          ECS_CONTAINER_PORT: ${{ vars.ECS_CONTAINER_PORT }}
        run: npm run destroy -- --auto-approve
